os: linux
language: generic
dist: xenial
services:
  - docker

before_install:
  - docker build -t manjurul/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manjurul/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-us-east-2-367084430254"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
